-- MySQL Script generated by MySQL Workbench
-- Mon May 16 22:12:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema byloja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema byloja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `byloja` DEFAULT CHARACTER SET utf8 ;
USE `byloja` ;

-- -----------------------------------------------------
-- Table `byloja`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byloja`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`produto` (
  `id_produto` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL DEFAULT '/padroes/sem_imagem.png',
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byloja`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`venda` (
  `id_venda` INT NOT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `byloja`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byloja`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `byloja`.`venda_produto` (
  `id_venda` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id_venda`, `id_produto`),
  INDEX `id_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `id_venda`
    FOREIGN KEY (`id_venda`)
    REFERENCES `byloja`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `byloja`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
